### ISSUE TITLE
Build prod release fails with erro

### ISSUE THREAD

**Issue by xixiaofinland** [ionic-team/ionic2-starter-aws#17]
Hi,

My app with starter kit runs well both in browser and Android tablet during development.
When I try to build prod release by `ionic cordova build android --prod --release`, error like below appears.

I assume the error roots from here `IonicModule.forRoot(MyApp, new AwsConfig().load())` in `app.module.ts`

Thanks,
Xi

```
Error: Error encountered resolving symbol values statically. Calling function 'AwsConfig', 

function calls  are not supported. Consider replacing the function or lambda with a reference to an exported function, 

resolving symbol AppModule in app.module.ts, resolving symbol  AppModule
```

**Comment by Xixiao007** [comment]
I fixed it by modifying `app.module.ts` to

```
export function addAws() {
  return new AwsConfig().load();
}

@NgModule({
  imports: [
     ....
    IonicModule.forRoot(MyApp, addAws)
  ],
})
```

**Comment by Xixiao007** [comment]
It seems a solution by

```
export function addAws() {
  return new AwsConfig().load();
}
@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp, addAws())
  ],
......
```

**Comment by AR3X** [comment]
Hi, I have same bug,
have you this problem solved?
This comming when i use the **--prod** parameter

**Comment by xixiaofinland** [comment]
@AR3X no I didn't :(

**Comment by mlynch** [comment]
Thanks for the heads up, we will take a look

**Comment by mlynch** [comment]
Hey all, this should be fixed now. Can you confirm? Thanks.

**Comment by MikeOShay** [comment]
For me, this resolved the symbol value error, but now I'm getting "Both UserPoolId and ClientId are required." when I try to sign in. I made the same changes, declaring AWS, removing AwsConfig.load, and changing the pool/client to "window as any".

**Comment by MShayOffice** [comment]
I was having the same error and have made all the changes from the latest commit. The symbol resolving error is gone, but now when I try to log in, it fails, returning "Both UserPoolId and ClientId are required."

I've checked over and over, all the changes are there, it doesn't log in anymore even if I add the AwsConfig().load() back in. Could I be missing something required to use the "window as any" syntax?

**Comment by xixiaofinland** [comment]
Hi,

I confirm with @MikeOShay, it seems those settings were not successfully loaded despite that the error is gone.

I decided to give up on using this starterkit as I needed to make progress.
I strongly recommend to wrap these settings into a module that can be easily loaded into app.module.ts @NgModule in Ionic, instead of what the package has now, which is very "not ionic way".

It is a high demanded kit, needs a bit polishing. Keep up :)

**Comment by mlynch** [comment]
Hmm, will try another take. The way the aws config requires the values to be set was conflicting w/ AoT and thought this would resolve that but it created another issue

**Comment by mlynch** [comment]
Okay I tried something else and it appears to be resolved and working (this time I actually tested properly)

**Comment by AR3X** [comment]
Thanks!
