### ISSUE TITLE
Scope bugs when running app in Google Chrome.

### ISSUE THREAD

**Issue by jamey-taylor** [ionic-team/ionic2-starter-aws#20]
I get "this.isAuthenticated is undefined" after login and "this.refreshTasks" is undefined after adding a task.  To fix my local copy, I changed the callback to a typescript fat arrow in user.ts line 36  and tasks.ts line 78.

**Comment by chadamodio** [comment]
Do you have the code that fixed this.refreshTasks error? Thanks in advance.

**Comment by jamey-taylor** [comment]
Sure thing! Here's what I did on my local:


user.ts 36:     'onSuccess': (result) => {
tasks.ts 78:   }, (err, data) => {

**Comment by chadamodio** [comment]
much easier than my changes! thanks

**Comment by kopahead** [comment]
I am getting ```ionic this.refreshTasks is not a function``` on chrome after creating a task.
 When I refresh the page I can see the task though

Any one else came across this?

**Comment by chadamodio** [comment]
@kopahead change the code shown in @jamey-taylor response. It fixed the issue for me.

**Comment by mlynch** [comment]
Should be resolved in PR #21, thanks!
