### ISSUE TITLE
Runtime Errors (chrome)

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic2-starter-aws#24]
Hi,
I have Runtime Errors like "this.isAuthenticated is not a function" and "this.refreshTasks is not a function" ???
Any idea ?

**Comment by ghost** [comment]
Hi,
you must change user.ts and tasks.ts and put outside of the concerned functions something like:

`let self = this;`

and use 

`self.isAuthenticated()...`

afterwards.

**Comment by ghost** [comment]
OK thanks.

**Comment by janpio** [comment]
So the project is currently broken in the state that is available for download here?

**Comment by ghost** [comment]
I saw many pull requests fixing the issues.

**Comment by janpio** [comment]
Could you provide link to those please?

**Comment by ghost** [comment]
Issue #20 seems to be the same and there are fixing answers, no ?

**Comment by janpio** [comment]
Yes, another issue thread. Could someone please just submit a PR with these changes so the maintainer can just merge this and get it fixed properly?
