### ISSUE TITLE
Importing the mobile hub project fails

### ISSUE THREAD

**Issue by tinomen** [ionic-team/ionic2-starter-aws#31]
I attempted to upload the project config file (mobile-hub-project.zip) and received this error:

The security token included in the request is invalid. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 78d893a4-6cd6-11e7-bbed-5d0ccbc06132) 

I don't see this listed in the yml file but assume it's related to the sign-in config. Is this a permissions issue?

**Comment by mlynch** [comment]
Looks like #33 is related? Looking into this

**Comment by mlynch** [comment]
I just tried uploading the zip and it worked fine for me. Can you try again? I don't think #33 is related now that I think about it.

Could have been a temporary issue on AWS's side
