### ISSUE TITLE
AWS.config.credentials.identityId is undefined

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic2-starter-aws#42]
After successful login, AWS.config.credentials.identityId seems undefined. I realize that an issue but I don't know how can I handle:

First login: Old user identityId
Second login: Empty user
Third login: Correct id

It can be related with missing credentials in config issue but the solution in issue is not worked for me. It causes always undefined id.

**Comment by mqasem92** [comment]
add AWS.config.credentials.clearCachedId(); on the logout

```
logout() {
    this.user = null;
    this.cognito.getUserPool().getCurrentUser().signOut();
    AWS.config.credentials.clearCachedId();
  }
```

Any may you need to add refresh after new AWS.CognitoIdentityCredentials
```
//to refresh new user login and id data
          AWS.config.credentials.refresh(function () {
            console.log('USER-SERVICE:LOGIN:AWS.config.credentials.identityId -> ' + AWS.config.credentials.identityId);
          });
```

**Comment by dnuch** [comment]
@mqasem92 the code you posted fixes the undefined Id issue on multiple logins, but how do we make session token not undefined on second login - or rather make consecutive credentials perform the same.

**Comment by ndnparis** [comment]
I have the same issue. I mean the AWS Mobile Hub is not mature yet.
One day it works and another day it stops working. I have spent days and weeks for these issues.
The big worry for me is that Amazon will drop this functionality, one day. I am really exhausted!
So which alternative would you advise me? Azure, Firebase or Google?

**Comment by mlynch** [comment]
Should be resolved now, thanks!
