### ISSUE TITLE
Too Many Buckets - AWS

### ISSUE THREAD

**Issue by cesarcastmore** [ionic-team/ionic2-starter-aws#46]
I am trying to import the zip in my aws account but I have the message

Unable to create Amazon S3 bucket for deployment artifacts. You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: 

Could anybody help me what it means ?

**Comment by mlynch** [comment]
sounds like your account has too many S3 buckets so the auto project creation is failing. This is a better question for AWS support. Thanks!
